### PR TITLE
m2e-ajdt updated for m2e 1.0

### PR DESCRIPTION
**Pull request by ilx**
Hi,

I made some changes to m2e-ajdt in order to make it work with m2e 1.0.
Please take a look and give some advice.

Kind regards,

Ivica Loncar

### CODE REVIEW

**Comment by ifedorenko** [comment]
We need signed CLA in order to accept this patch. http://www.sonatype.org/SonatypeCLA.pdf

**Comment by aeisenberg** [comment]
Hi,

What's the status of this pull request?  Are the problems here bureaucratic, or are there some technical problems?

I am looking to put out an update site for the ajdt configurator on the springsource servers.

**Comment by ifedorenko** [comment]
We can't accept patches without signed CLA so we have not looked at the patches yet.

**Comment by ilx** [comment]
I'm on a vacation filling the CLA. I  have to find time, go to postal office, fax it and so on.

**Comment by ghost** [comment]
@ilx, please really read the CLA before signing it.

@Sonatype, what are you smoking? It's the first time I see something like this in open source world. "Grant of Copyright License to Sonatype, Grant of Patent License to Sonatype": stop doing open source if you're so far form its spirit. Talking of copyright and patent granting is quite injurious in this place. What did you expect? That some ghostwriters pushes you some patches with the absolute satisfaction that you take all the merit? Open source is sharing, not just taking.

You make really good products but there are other ways for making money with it than that sort of CLA and takeover bid on other OSS with massive commits (you said Maven?).

And, franckly, you are talking about an indecent CLA to accept a patch on GitHub for an open source AJDT connector to M2Eclipse. A bit counter productive I think.

**Comment by ifedorenko** [comment]
Yes, please do read the CLA and make sure you understand what you are signing. 

Nobody is forcing anybody to contribute their patches to Sonatype. You can choose to sign the CLA or you can choose to maintain your fork. The decision is yours, as long as your obey EPL requirements. For what it's worth, Sonatype needs the CLA to make it easier to contribute the code to Eclipse in the future.

**Comment by aeisenberg** [comment]
Igor, if this is (going to be) an eclipse project, shouldn't the contributor's agreement be with Eclipse and not Sonatype?

**Comment by ifedorenko** [comment]
Frankly, this goes way beyond my understanding of the legal implications of this. I know that signed CLA made m2e contribution to Eclipse much easier (we basically did not have to contact every external contributor). And to me clear, to the best of my knowledge there are no immediate plans to contribute m2e-ajdt code to Eclipse. if you have any further legal question, please contact community@sonatype.com, i.e. email mentioned in the CLA.

**Comment by ilx** [comment]
I've faxed signed cla so there should be no obstacles anymore. Otoh it's not very friendly approach for an opensource project. It takes too much energy. I understand sonatypes need but it just feels wrong, so please forward this to someone who can really open source or donate this project to eclipse. I had much more pleasant experience contributing to ajdt than to ajdt configurator.

**Comment by hopperd** [comment]
Now that all the legal stuff is worked out, when can we expect this pull request to be fulfilled?

**Comment by ifedorenko** [comment]
I spoke to our legal folks and asked them to double-check but they never got the fax. Can you please scan and email the signed CLA to community@sonatype.com and CC me (ifedorenko at sonatype dot com) so I can expedite the processing. Thank you in advance and sorry for the inconvenience.

**Comment by ilx** [comment]
Hi, I have just sent an email with signed CLA attached to it.

**Comment by ifedorenko** [comment]
I am having difficulties applying this patch to the current master. Are you sure you want me to pull 24 commits? This does not look right.

**Comment by ilx** [comment]
I'm not that experienced with github, so I will close this pull request.
If there's a need for a merge you can always merge manually .

**Comment by ifedorenko** [comment]
i still I need to know what to merge. what commit do you want me to merge?

**Comment by ilx** [comment]
I'm doing this manually so I apologize if I missed something:
- 7750f77d99244bed5371
- cc1fe00b82cb3b0aa6c9
- 1733ec05733c50b81d73
- 0a1908690e8ae4d863d9
- bf8d0165158c9b6c5b11
- 37bfe692ed9b93532be2
- b6b58326fff218c9bbea

There are more commits by Andrew Eisenberg and me, but that's after I opened the request.

**Comment by aeisenberg** [comment]
Is there any reason not to apply all of the commits?  What has changed?  The commits that I made are making the junit tests pass.  As far as I know, for years they were failing (or at least they were failing for me when I first looked at the AJDT configurator 2 years ago).

**Comment by ifedorenko** [comment]
I could not apply this pull request to the master HEAD as of yesterday. I will also have to get CLAs from all contributors and hesitated to even mention this ;-)

**Comment by ilx** [comment]
@Andrew: famous CLA :)))

@Igor: If we ever meet you owe me a beer - you convinced me to stop my vacation - wait in a line at the post office for an hour and pay almost 7$ for a fax that never got to Sonatypes legal department. :-)

**Comment by aeisenberg** [comment]
Hmmm...not a big fan of this CLA, but I will sign it and fax it.  Thankfully, I am not currently on vacation and do have easy access to that old skool technology.

Do I really need to send the original via snail mail?

**Comment by ifedorenko** [comment]
don't fax, email!

**Comment by aeisenberg** [comment]
signed and emailed.

**Comment by ifedorenko** [comment]
thank you. so... do you want me to take HEAD of master branch from https://github.com/ilx/m2eclipse-ajdt and put it here?

**Comment by ilx** [comment]
@igor: that would be great. 

Btw. I just created another configurer  (https://github.com/ilx/m2e-querydsl). Is there a way to make it more public so people test it? How can I contribute to m2e discovery?

**Comment by aeisenberg** [comment]
@Igor thanks
@Ivica good question.  I'd like to do the same for groovy-eclipse.

**Comment by ifedorenko** [comment]
generally, I'd send you to m2e-dev@ecilpse.org but under the threat of owing more beer I'll answer here ;-)

to ask for feedback, testing, etc, email m2e-users@eclipse.org and see if anyone is interested.

to submit new entries to discovery catalog read http://wiki.eclipse.org/Submitting_M2E_marketplace_entries

**Comment by cforce** [comment]
Can't find m2eclipse-ajdt connector in eclipse indigo! Is it already  in the marketplace?

**Comment by aeisenberg** [comment]
The only update site that I know of is here:
http://dist.springsource.org/release/AJDT/configurator/

I am still waiting for the m2e team to add this connector to the m2e
discovery marketplace.

On Tue, Nov 15, 2011 at 2:05 PM, cforce
reply@reply.github.com
wrote:

**Comment by cforce** [comment]
.. yeah, why don't they do so??its months ago now

**Comment by cforce** [comment]
The link "http://dist.springsource.org/release/AJDT/configurator/" does not work either .. so i only can build it myself? 
I realy don't understand sonatype why the treat aspectj support in m2e so badly.

**Comment by aeisenberg** [comment]
Why is this not working for you?

On Wednesday, November 16, 2011, cforce <
reply@reply.github.com>
wrote:

**Comment by cforce** [comment]
Sorry i have no idea how i shall use this to get my update site or a jar? Which of the xml paramters shall i take for what?
Thre is no link, no maven artifact id ..
I am noob to this kind of artifact reference.

**Comment by aeisenberg** [comment]
This is an Eclipse update site.  To use, you must start Eclipse, go to
Help -> Install new software.  And then paste the URL into the "Work
with" box.  When the update sites appear, select the AJDT configurator
and follow the instructions.

Oh, and one more thing, in order to use the AJDT confiigurator, you
must already have AJDT (AspectJ Development Tools) installed.  You can
get them here:  http://download.eclipse.org/tools/ajdt/37/update.
(install these first, the same way as you do the configurator).

On Thu, Nov 17, 2011 at 1:54 AM, cforce
reply@reply.github.com
wrote:

**Comment by micw** [comment]
Hi. What is the state of this pull request?
The official version at https://github.com/sonatype/m2eclipse-ajdt is not working anymore with recent m2e versions (e.g. running "Update project configuration" will remove all aspect libraries, the add dialog does not recognize that the project is a maven project).

I tried to build your version for my own but it fails with: You requested to install 'org.eclipse.m2e.sdk.feature.feature.group [1.0.0.201106052308]' but it could not be found

**Comment by ilx** [comment]
It's deprecated. Andrew Eisenberg (one of the two people behind AJDT) practically took over the code and plugin.

p2 repo is available at:
http://dist.springsource.org/release/AJDT/configurator/

**Comment by aeisenberg** [comment]
Just got the tycho build working for this project today.  Jason and Igor are working on the getting the catalog going for m2e v1.1, so I expect the ajdt configurator for m2e 1.1 will be available shortly.  The contents of the p2 repository that Ivica points to is basically up to date.  I don't know where the new repository will be located, but there should be an announcement on m2e users mailing list.

**Pull request closed without merging**
