### PR TITLE
Move to m2e-core

### PR DESCRIPTION
**Pull request by cheleb**
Hi,
 Please could you review this request, it's just an attempt to migrate to the m2e-core 1.0 with lifecycle management. 
 Test project is OK, and on my project all seem alright.
 Thanks.
 Best regards,
Olivier.

### CODE REVIEW

**Comment by ifedorenko** [comment]
Does Sonatype have your signed CLA on file? http://www.sonatype.org/SonatypeCLA.pdf

**Comment by cheleb** [comment]
Not yet ...
Do you want it ? By email, our mail ?

On Sat, Sep 24, 2011 at 6:24 PM, ifedorenko <
reply@reply.github.com>wrote:

> Does Sonatype have your signed CLA on file?
> http://www.sonatype.org/SonatypeCLA.pdf
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sonatype/m2eclipse-ajdt/pull/4#issuecomment-2187086

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by ifedorenko** [comment]
yes, please email signed scanned copy to the community@sonatype.com

**Comment by cheleb** [comment]
Just done.

On Sat, Sep 24, 2011 at 8:33 PM, ifedorenko <
reply@reply.github.com>wrote:

> yes, please email signed scanned copy to the community@sonatype.com
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sonatype/m2eclipse-ajdt/pull/4#issuecomment-2187604

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by ifedorenko** [comment]
FYI, I am still getting UT failures running m2e-ajdt build both on osx and linux.

Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 253.887 sec <<< FAILURE! testSimple01_import(org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest) Time elapsed: 243.194 sec <<< FAILURE! junit.framework.AssertionFailedError: Expected AJDT nature at junit.framework.Assert.fail(Assert.java:47) at junit.framework.Assert.assertTrue(Assert.java:20) at org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest.testSimple01_import(AjdtProjectConfiguratorTest.java:48) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at junit.framework.TestCase.runTest(TestCase.java:168) at junit.framework.TestCase.runBare(TestCase.java:134) at junit.framework.TestResult$1.protect(TestResult.java:110) at junit.framework.TestResult.runProtected(TestResult.java:128) at junit.framework.TestResult.run(TestResult.java:113) at junit.framework.TestCase.run(TestCase.java:124) at junit.framework.TestSuite.runTest(TestSuite.java:243) at junit.framework.TestSuite.run(TestSuite.java:238) at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83) at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62) at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140) at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127) at org.apache.maven.surefire.Surefire.run(Surefire.java:177) at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:72) at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577) at org.eclipse.equinox.launcher.Main.run(Main.java:1410) at org.eclipse.equinox.launcher.Main.main(Main.java:1386) testInterProject(org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest) Time elapsed: 10.662 sec <<< FAILURE! junit.framework.AssertionFailedError: Expected AJDT nature at junit.framework.Assert.fail(Assert.java:47) at junit.framework.Assert.assertTrue(Assert.java:20) at org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest.testInterProject(AjdtProjectConfiguratorTest.java:86) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at junit.framework.TestCase.runTest(TestCase.java:168) at junit.framework.TestCase.runBare(TestCase.java:134) at junit.framework.TestResult$1.protect(TestResult.java:110) at junit.framework.TestResult.runProtected(TestResult.java:128) at junit.framework.TestResult.run(TestResult.java:113) at junit.framework.TestCase.run(TestCase.java:124) at junit.framework.TestSuite.runTest(TestSuite.java:243) at junit.framework.TestSuite.run(TestSuite.java:238) at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83) at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62) at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140) at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127) at org.apache.maven.surefire.Surefire.run(Surefire.java:177) at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:72) at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:592) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577) at org.eclipse.equinox.launcher.Main.run(Main.java:1410) at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
Results : Failed tests: testSimple01_import(org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest) testInterProject(org.maven.ide.eclipse.ajdt.tests.AjdtProjectConfiguratorTest) Tests run: 2, Failures: 2, Errors: 0, Skipped: 0

**Comment by cheleb** [comment]
Sorry about that I've set the minamal version on the maven-aspectj-plugin to 1.4 (bad habit of use bleeding edge version).
I will relax this contrain to 1.0 ASAP (as soon as download.eclipse.org is reacheable :(  ).

**Comment by cheleb** [comment]
Hum I have to confess that I'm quite lost ...
Even if a change the version required of the maven-aspectj-plugin to [1.0,),
the configurator is never called during the integration test. But the same
pom is ok within eclipse.
So I guess there is something to do with something else :(
- target platform are needed for integration test ?
- I've noticed that the AbstractMavenProjectTestCase are not exported is
  there another class to use as base test ?
  Thanks in advance.

**Pull request merged**
